---
language: python
services: docker

python:
  - "2.7"  # centos 7
  - "3.6"
  - "nightly"
env:
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: ubuntu1404
  - MOLECULE_DISTRO: ubuntu1604
  - ANSIBLE_VERSION: 2.7
  - ANSIBLE_VERSION: 2.8

#install:
#  - echo pip install molecule docker

script:
  - env
