---
language: python
services: docker

python:
  - "2.7"  # centos 7
  - "3.6"
  - "nightly"
env:
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: ubuntu1604

#install:
#  - echo pip install molecule docker

script:
  - env
