---
language: python
services: docker

python:
  - "2.7"  # centos 7
  - "3.6"
  - "nightly"
env:
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: ubuntu1404
  - MOLECULE_DISTRO: ubuntu1604
  - ANSIBLE: "ansible==2.7"
  - ANSIBLE: "ansible==2.8"
  - ANSIBLE: "ansible==2.9"

#install:
#  - echo pip install molecule docker

before_install:
  - env
  - echo $MOLECULE_DISTRO
  - echo $VERSION
  - echo $ANSIBLE
install:
  - '[ -n "${ANSIBLE}" ] || ANSIBLE="ansible==2.8'
  - 'pip install ${ANSIBLE} molecule'

script:
  - molecule test
