---
language: python
services: docker

python:
  - "2.7"  # centos 7
  - "3.6"
  - "nightly"
env:
  - MOLECULE_DOCKER_IMAGE: "centos:7"
  - MOLECULE_DOCKER_IMAGE: "ubuntu:14.04"
  - MOLECULE_DOCKER_IMAGE: "ubuntu:16.04"
  - ANSIBLE: "ansible==2.7"
  - ANSIBLE: "ansible==2.8"
  - ANSIBLE: "ansible==2.9"

jobs:
  exclude:
    - python: "2.7"
      env: ANSIBLE="ansible==2.9"
#install:
#  - echo pip install molecule docker

before_install:
  - echo $MOLECULE_DOCKER_IMAGE
  - echo $ANSIBLE
install:
  - '[ -n "${ANSIBLE}" ] || ANSIBLE="ansible==2.8"'
  - 'echo $ANSIBLE'
  - 'echo "${ANSIBLE}"'
  - 'pip install "${ANSIBLE}" "molecule[docker]"'
  - 'pip freeze'
  - 'ansible --version'

script:
  - molecule test
