---
language: python
services: docker

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
env:
  ansible:
    - "2.7"
    - "2.8"
  docker_image:
    - centos7
    - ubuntu1404
    - ubuntu1604

#install:
#  - echo pip install molecule docker

script:
  - env
